actions:
  i3-restart: i3-msg restart
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_ario_profiles.xml:
    dst: ~/.config/ario/profiles/profiles.xml
    src: config/ario/profiles/profiles.xml
  f_bira_custom.zsh-theme:
    dst: ~/.oh-my-zsh/themes/bira_custom.zsh-theme
    src: oh-my-zsh/themes/bira_custom.zsh-theme
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gtk_theme:
    dst: ~/.themes/My_Fancy_Theme/
    src: themes/My_Fancy_Theme/
  f_i3:
    dst: ~/.i3/
    src: i3/
  f_i3_config:
    actions:
    - i3-restart
    dst: ~/.i3/config
    src: i3/config
  f_i3exit.py:
    dst: ~/.i3/i3exit.py
    src: i3/i3exit.py
  f_i3status.conf:
    actions:
    - i3-restart
    dst: ~/.i3/i3status.conf
    src: i3/i3status.conf
  f_i3status2.conf:
    actions:
    - i3-restart
    dst: ~/.i3/i3status2.conf
    src: i3/i3status2.conf
  f_radio.sh:
    dst: ~/scripts/radio/radio.sh
    src: scripts/radio/radio.sh
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  f_viewnior.conf:
    dst: ~/.config/viewnior/viewnior.conf
    src: config/viewnior/viewnior.conf
  f_vimperatorrc:
    dst: ~/.vimperatorrc
    src: vimperatorrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zsh_arch:
    dst: ~/.zsh_arch
    src: zsh_arch
  f_zsh_defaults:
    dst: ~/.zsh_defaults
    src: zsh_defaults
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  ant:
    dotfiles:
    - f_zshrc
    - f_zsh_defaults
    - f_zsh_arch
    - f_bira_custom.zsh-theme
    - f_vimrc
    - f_vimperatorrc
    - f_radio.sh
    - f_xinitrc
    - f_xresources
    - f_i3
    - f_screenrc
    - f_viewnior.conf
    - f_ario_profiles.xml
    - f_gitconfig
    - f_gtk_theme
  fuckup:
    dotfiles:
    - f_zshrc
    - f_zsh_defaults
    - f_zsh_arch
    - f_bira_custom.zsh-theme
    - f_vimrc
    - f_xinitrc
    - f_xresources
    - f_vimperatorrc
    - f_i3exit.py
    - f_screenrc
    - f_radio.sh
    - f_i3status.conf
    - f_i3status2.conf
