actions:
  dunst-restart: killall dunst; notify-send -t 2000 -i face-sick "Dunst restarted"
  font-cache-refresh: fc-cache -f -v
  i3-restart: ~/.i3/i3restart.sh
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_gtk_theme:
    dst: ~/.themes/My_Fancy_Theme/
    src: themes/My_Fancy_Theme/
  d_i3:
    actions:
    - i3-restart
    dst: ~/.i3/
    src: i3/
  d_syncit:
    dst: ~/scripts/syncit/
    src: scripts/syncit/
  d_zsh:
    dst: ~/.zsh
    src: zsh
  f_ario_profiles.xml:
    dst: ~/.config/ario/profiles/profiles.xml
    src: config/ario/profiles/profiles.xml
  f_bira_custom.zsh-theme:
    dst: ~/.oh-my-zsh/themes/bira_custom.zsh-theme
    src: oh-my-zsh/themes/bira_custom.zsh-theme
  f_dunstrc:
    actions:
    - dunst-restart
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gtk3_settings.ini:
    dst: ~/.config/gtk-3.0/settings.ini
    src: config/gtk-3.0/settings.ini
  f_hedgewars.desktop:
    dst: ~/.local/share/applications/hedgewars.desktop
    src: local/share/applications/hedgewars.desktop
  f_keylayouttoggle.sh:
    dst: ~/scripts/keylayouttoggle.sh
    src: scripts/keylayouttoggle.sh
  f_mfixx_custom.ttf:
    actions:
    - font-cache-refresh
    dst: ~/.local/share/fonts/MFixx_custom.ttf
    src: local/share/fonts/MFixx_custom.ttf
  f_pypirc:
    dst: ~/.pypirc
    src: pypirc
  f_pythonrc:
    dst: ~/.pythonrc
    src: pythonrc
  f_radio.sh:
    dst: ~/scripts/radio/radio.sh
    src: scripts/radio/radio.sh
  f_screenrc:
    dst: ~/.screenrc
    src: screenrc
  f_syncit.desktop:
    dst: ~/.local/share/applications/syncit.desktop
    src: local/share/applications/syncit.desktop
  f_viewnior.conf:
    dst: ~/.config/viewnior/viewnior.conf
    src: config/viewnior/viewnior.conf
  f_vimperatorrc:
    dst: ~/.vimperatorrc
    src: vimperatorrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_wrapper.sh:
    dst: ~/scripts/wrapper.sh
    src: scripts/wrapper.sh
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  ant:
    dotfiles:
    - d_gtk_theme
    - d_i3
    - d_syncit
    - d_zsh
    - f_ario_profiles.xml
    - f_bira_custom.zsh-theme
    - f_dunstrc
    - f_gitconfig
    - f_gtk3_settings.ini
    - f_hedgewars.desktop
    - f_mfixx_custom.ttf
    - f_pypirc
    - f_pypirc
    - f_radio.sh
    - f_screenrc
    - f_viewnior.conf
    - f_vimperatorrc
    - f_vimrc
    - f_wrapper.sh
    - f_xinitrc
    - f_xresources
    - f_zshrc
  baldur:
    dotfiles:
    - d_zsh
    - f_bira_custom.zsh-theme
    - f_gitconfig
    - f_pypirc
    - f_pythonrc
    - f_screenrc
    - f_vimrc
    - f_zshrc
  fuckup:
    dotfiles:
    - d_gtk_theme
    - d_i3
    - d_syncit
    - d_zsh
    - f_ario_profiles.xml
    - f_bira_custom.zsh-theme
    - f_dunstrc
    - f_gitconfig
    - f_gtk3_settings.ini
    - f_hedgewars.desktop
    - f_keylayouttoggle.sh
    - f_mfixx_custom.ttf
    - f_pypirc
    - f_pythonrc
    - f_radio.sh
    - f_screenrc
    - f_syncit.desktop
    - f_viewnior.conf
    - f_vimperatorrc
    - f_vimrc
    - f_wrapper.sh
    - f_xinitrc
    - f_xresources
    - f_zshrc
