config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bira_custom.zsh-theme:
    dst: ~/.oh-my-zsh/themes/bira_custom.zsh-theme
    src: oh-my-zsh/themes/bira_custom.zsh-theme
  f_radio.sh:
    dst: ~/scripts/radio/radio.sh
    src: scripts/radio/radio.sh
  f_vimperatorrc:
    dst: ~/.vimperatorrc
    src: vimperatorrc
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_zsh_arch:
    dst: ~/.zsh_arch
    src: zsh_arch
  f_zsh_defaults:
    dst: ~/.zsh_defaults
    src: zsh_defaults
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  ant:
    dotfiles:
    - f_zshrc
    - f_zsh_defaults
    - f_zsh_arch
    - f_bira_custom.zsh-theme
    - f_vimrc
    - f_vimperatorrc
    - f_radio.sh
    - f_xinitrc
    - f_xresources
  fuckup:
    dotfiles:
    - f_zshrc
    - f_zsh_defaults
    - f_zsh_arch
    - f_bira_custom.zsh-theme
    - f_vimrc
    - f_xinitrc
    - f_xresources
    - f_vimperatorrc
